Fty srr cmd
42ity/fty-srr pull request #40
Opened 2021-01-28 15:55 UTC by stark-dev

First SRR cli implementation, based on `MessageBus` requests

2021-01-28 16:04 UTC, perrettecl approved these changes

2021-01-28 16:04 UTC, perrettecl commented on server/src/fty-srr-cmd.cc
> +#define DEFAULT_TIME_OUT 300
300 s seems short for me. Better to have 1h

2021-01-28 16:06 UTC, perrettecl requested changes
Update of timeout, otherwise it's ok for me.

2021-01-28 17:13 UTC, merged

2021-01-28 19:17 UTC, etnKlendathu reviewed
just added 2 stupid notes...

2021-01-28 19:17 UTC, etnKlendathu commented on server/src/fty-srr-cmd.cc
> +std::ostream &operator<< (std::ostream &os, const std::vector<T> &vec)
fty::implode

2021-01-28 19:17 UTC, etnKlendathu commented on server/src/fty-srr-cmd.cc
> +dto::UserData sendRequest (const std::string &action,
how long string len do you have in clang format?

2021-01-29 08:59 UTC, stark-dev commented on server/src/fty-srr-cmd.cc
> +std::ostream &operator<< (std::ostream &os, const std::vector<T> &vec)
Nice, I'll have a look to that

2021-01-29 09:00 UTC, stark-dev commented on server/src/fty-srr-cmd.cc
> +dto::UserData sendRequest (const std::string &action,
Probably it was old template, I will update it